server {
    listen 80;

    root usr/share/nginx/html;

    location = / {
        return 302 /pages/login.html;
    }

    location /api/ {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ = 404;
    }
}