services:
  db:
    image: mysql:8.4
    container_name: pantrychef-db
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - pantrychef_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pantrychef_mysql_data:


